
const iconsList: {[key: string]: string} = {
    'alert': 'coem-admin-icon-Alert',
    'align-center': 'coem-admin-icon-Align--Center',
    'align-justify': 'coem-admin-icon-Align-Justify',
    'align-left': 'coem-admin-icon-Align-Left',
    'align-right': 'coem-admin-icon-Align-Right',
    'archive': 'coem-admin-icon-Archive',
    'arrow-down-1': 'coem-admin-icon-Arrow-Down-1',
    'arrow-down-2': 'coem-admin-icon-Arrow-Down-2',
    'arrow-left':   'coem-admin-icon-Arrow-Left',
    'arrow-right-1': 'coem-admin-icon-Arrow-Right-1',
    'arrow-right-2': 'coem-admin-icon-Arrow-Right-2',
    'attachment' : 'coem-admin-icon-Attachment',
    'attachment-1' : 'coem-admin-icon-Attachment-1',
    'bell' : 'coem-admin-icon-Bell',
    //'bell-notification' : 'coem-admin-icon-Bell--Notification',
    'bold' : 'coem-admin-icon-Bold',
    'calendar': 'coem-admin-icon-Calendar\n',
    'camera' : 'coem-admin-icon-Camera',
    'cart' : 'coem-admin-icon-Cart',
    'chart': 'coem-admin-icon-Chart',
    'chat': 'coem-admin-icon-Chat',
    'check' : 'coem-admin-icon-Check',
    //'chat-notification': 'coem-admin-icon-Chat--Notification',
    'check-square': 'coem-admin-icon-Check-Square',
    'coffee' : 'coem-admin-icon-Coffee',
    'contacts': 'coem-admin-icon-Contacts\n',
    'copy' : 'coem-admin-icon-Copy',
    'cross': 'coem-admin-icon-Cross',
    'csv': 'coem-admin-icon-CSV',
    'delete': 'coem-admin-icon-Delete',
    'discount': 'coem-admin-icon-Discount',
    'dollar' : 'coem-admin-icon-Dollar',
    'dollar-fill': 'coem-admin-icon-Dollar-Fill',
    'download' : 'coem-admin-icon-Download',
    'drag': 'coem-admin-icon-Drag',
    'edit': 'coem-admin-icon-Edit',
    'excel': 'coem-admin-icon-Excel',
    'facebook': 'coem-admin-icon-Facebook',
    'filter': 'coem-admin-icon-Filter',
    'filter-2': 'coem-admin-icon-Filter-2',
    'flag': 'coem-admin-icon-Flag',
    'folder': 'coem-admin-icon-Folder',
    'folder-fill': 'coem-admin-icon-Folder-Fill',
    'folder-move': 'coem-admin-icon-Folder-Move',
    'font': 'coem-admin-icon-Font',
    'grid': 'coem-admin-icon-Grid',
    'hide': 'coem-admin-icon-Hide',
    'image': 'coem-admin-icon-Image',
    'important': ' coem-admin-icon-Important',
    'important-fill': 'coem-admin-icon-Important-Fill',
    'inbox': 'coem-admin-icon-Inbox',
    'instagram': 'coem-admin-icon-Instagram',
    'italic': 'coem-admin-icon-Italic',
    'like': 'coem-admin-icon-Like',
    'like-fill': 'coem-admin-icon-Like-Fill',
    'link': 'coem-admin-icon-Link',
    'list': 'coem-admin-icon-List',
    'list-2': 'coem-admin-icon-List-2',
    'lock' : 'coem-admin-icon-Lock',
    'logout': 'coem-admin-icon-Logout',
    'mail': 'coem-admin-icon-Mail',
    'map': 'coem-admin-icon-Map',
    'menu': 'coem-admin-icon-Menu',
    'minus' : 'coem-admin-icon-Minus',
    'more': 'coem-admin-icon-More',
    'move': 'coem-admin-icon-Move',
    'music': 'coem-admin-icon-Music',
    'notebook': 'coem-admin-icon-Notebook',
    'numbered-list': 'coem-admin-icon-Numbered-List',
    'pantone': 'coem-admin-icon-Pantone',
    'pdf': 'coem-admin-icon-PDF',
    'phone': 'coem-admin-icon-Phone',
    'pin': 'coem-admin-icon-Pin',
    'plus': 'coem-admin-icon-Plus',
    'printer': 'coem-admin-icon-Printer',
    'project': 'coem-admin-icon-Project',
    'pushpin': 'coem-admin-icon-Pushpin',
    'read-mail': 'coem-admin-icon-Read-Mail',
    'reply': 'coem-admin-icon-Reply\n',
    'reply-all': 'coem-admin-icon-Reply-All',
    'search': 'coem-admin-icon-Search',
    'send': 'coem-admin-icon-Send',
    'send-fill': 'coem-admin-icon-Send-Fill',
    'settings': 'coem-admin-icon-Settings',
    'share': 'coem-admin-icon-Share',
    'shopping': 'coem-admin-icon-Shopping',
    'show': 'coem-admin-icon-Show',
    'smartphone': 'coem-admin-icon-Smartphone',
    'smile': 'coem-admin-icon-Smile',
    'sort': 'coem-admin-icon-Sort',
    'sport': 'coem-admin-icon-Sport',
    'square': 'coem-admin-icon-Square',
    'star' : 'coem-admin-icon-Star',
    'star-fill': 'coem-admin-icon-Star-Fill',
    'sun': 'coem-admin-icon-Sun',
    'tag': 'coem-admin-icon-Tag',
    'tasks': 'coem-admin-icon-Tasks',
    'text': 'coem-admin-icon-Text',
    'time': 'coem-admin-icon-Time',
    'travel': 'coem-admin-icon-Travel',
    'twitter': 'coem-admin-icon-Twitter',
    'underline': 'coem-admin-icon-Underline',
    'update': 'coem-admin-icon-Update',
    'upload': 'coem-admin-icon-Upload',
    'upload-cloud': 'coem-admin-icon-Upload-Cloud',
    'user': 'coem-admin-icon-User',
    'user-add': 'coem-admin-icon-User-Add',
    'user-fill': 'coem-admin-icon-User-Fill',
    'zap': 'coem-admin-icon-Zap',
}


export default iconsList;
